<?php


namespace App\Shared\Exception;

final class ErrorCodes
{
    // Users
    public const USER_NOT_FOUND = 'USER_NOT_FOUND';
    public const USERNAME_REQUIRED = 'USERNAME_REQUIRED';
    public const PASSWORD_REQUIRED = 'PASSWORD_REQUIRED';
    public const USERNAME_AND_PASSWORD_REQUIRED = 'USERNAME_AND_PASSWORD_REQUIRED';
    public const USERNAME_TOO_SHORT = 'USERNAME_TOO_SHORT';
    public const PASSWORD_TOO_SHORT = 'PASSWORD_TOO_SHORT';
    public const USERNAME_ALREADY_EXISTS = 'USERNAME_ALREADY_EXISTS';
    public const USER_NOT_CREATED = 'USER_NOT_CREATED';
    public const USER_NOT_UPDATED = 'USER_NOT_UPDATED';
    public const USER_NOT_DELETED = 'USER_NOT_DELETED';
    public const USERNAME_UPDATE_FORBIDDEN = 'USERNAME_UPDATE_FORBIDDEN';
    public const AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS';
    public const ROLE_NOT_FOUND = 'ROLE_NOT_FOUND';
    public const ROLE_ALREADY_EXISTS = 'ROLE_ALREADY_EXISTS';
    public const ROLE_NOT_CREATED = 'ROLE_NOT_CREATED';
    public const PERMISSION_NOT_FOUND = 'PERMISSION_NOT_FOUND';
    public const PERMISSION_ALREADY_EXISTS = 'PERMISSION_ALREADY_EXISTS';
    public const  PERMISSION_NOT_CREATED = "PERMISSION_NOT_CREATED";
    public const  PERMISSION_CANNOT_UPDATED = "PERMISSION_CANNOT_UPDATED";
    public const ROLE_PERMISSION_NOT_ADDED = "ROLE_PERMISSION_NOT_ADDED";
    public const ROLE_PERMISSION_CANNOT_DELETE = "ROLE_PERMISSION_CANNOT_DELETE";
}
